### ISSUE TITLE
[gstreamer] Productionize/Update gstreamer dvswitch plugin

### ISSUE THREAD

**Issue by parx** [timvideos/getting-started#15]
# Brief explanation

The [dvswitch gstreamer plugin](https://github.com/timvideos/gst-plugins-dvswitch) is an important part of a migration scheme from dvswitch to newer technologies. This plugin could use a bunch of work to make it better.

Full list of outstanding issues with the plugin can be found at https://github.com/timvideos/gst-plugins-dvswitch/issues

## Expected results

 * Ideal -- gst-plugins-dvswitch becomes a standard gstreamer plugin.
 * Realistic -- gst-plugins-dvswitch is more reliable and code higher standard.

# Detailed Explanation

The following tasks are the minimum things that need to be finished;
 * Porting plugin to support both gstreamer0.10 and gstreamer1.x
 * Add testing infrastructure for making sure the plugin works reliably.
 * Add auto-reconnect on disconnection support.

The dvswitch plugin is used by https://github.com/timvideos/dvsource-v4l2-other to send data from a v4l2src source to DVSwitch.

Read the README files for both repositories;
 * https://github.com/timvideos/dvsource-v4l2-other/blob/dvswitchsink/README.md
 * https://github.com/timvideos/gst-plugins-dvswitch/blob/master/README.md

## Further reading

 * [GStreamer Plugin Writer's Guide](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/pwg/html/)
 * [DVSwitch](http://dvswitch.alioth.debian.org/wiki/)
 * [DVSwitch Components](http://dvswitch.alioth.debian.org/wiki/component_interaction/)
 * https://github.com/timvideos/dvsource-v4l2-other

# Knowledge Prerequisites

 * C programming knowledge.

# Contacts

 * **Potential Mentors:** @mithro @micolous @thaytan 
 * **Mailing list:** [timvideos@groups.google.com](https://groups.google.com/forum/#!forum/timvideos)

**Comment by aps-sids** [comment]
@mithro What's left to be done here?

**Comment by mithro** [comment]
I think this is done! 

We didn't end up with any testing infrastructure and I'm unsure about the auto-reconnect but they should just be issues on the repositories now I think.

We now even have packages at https://launchpad.net/~timvideos/+archive/ubuntu/dvswitch and even heading into Debian thanks to @stefanor
