### ISSUE TITLE
[Veyepar] Use avahi / zeroconfig to find our hosts on the network

### ISSUE THREAD

**Issue by iiie** [timvideos/getting-started#22]
# Brief explanation

We'd like to worry about fewer things, who wouldn't.
If we're setting a room with a couple of computers to record a talk, we shouldn't have to configure the network, it should "just work".
Avahi makes this easy, farther away host take longer to respond.
Make a setup program that updates the configs for either DVSwitch or GSTSwitch.
## Expected results
# Detailed Explanation

A much longer description of what the thing you want to do.
## Further reading
- https://code.google.com/p/pybonjour/
- Avahi examples;
  - See [PythonPublishExample](http://avahi.org/wiki/PythonPublishExample) for a relatively full service publisher using dbus-python.
  - See [PythonBrowseExample](http://avahi.org/wiki/PythonBrowseExample) for a simple service browser using dbus-python
# Knowledge Prerequisites

 *
# Contacts
- **Potential Mentors:** TimVideos / Veyepar Team
- **Mailing list:** [timvideos@groups.google.com](http://https://groups.google.com/forum/#!forum/timvideos/)

**Comment by CarlFK** [comment]
Ansible and systemd have mostly made this no longer an issue.
