### ISSUE TITLE
[streaming-system] Upgrade website to latest Django version

### ISSUE THREAD

**Issue by ApsOps** [timvideos/getting-started#28]
# Brief explanation

The website built initially on Django 1.4 with some updates to 1.5, needs to be upgraded to latest Django version since it has migrations included, many security and other updates.

## Expected results

The website runs on latest Django version.

# Detailed Explanation

FIXME: A much longer description of what the thing you want to do.

## Further reading

 * [Django Web Framework](https://www.djangoproject.com/)

# Knowledge Prerequisites

 * Python
 * Django
 * HTML/CSS

# Contacts

 * **Potential Mentors:** @mithro @CarlFK @codersquid 
 * **Mailing list:** [timvideos@groups.google.com](http://https://groups.google.com/forum/#!forum/timvideos/)

**Comment by aps-sids** [comment]
@mithro Please add appropriate labels here. I don't have access permissions, I guess.

**Comment by mithro** [comment]
I believe this was done by @micolous?
