### ISSUE TITLE
[streaming-system #4] Add bug / feedback reporting from end users system

### ISSUE THREAD

**Issue by mithro** [timvideos/getting-started#4]
More technical details at [Streaming System #4](https://github.com/timvideos/streaming-system/issues/4)

# Brief Explanation

Create a website/webpage which records bug / feedback information from an **end user**. You can't assume that the users know anything about bugs reporting, their own system or the TimVideos streaming system.

## Expected results

The tools will collect details about the conditions and outcomes of any bugs in the user interface.

# Detailed Explanation

A user may face issues in watching streams, some possibilities include;
 * Low internet bandwidth
 * Outdated browser or operating system
 * Problems at TimVideos server end

Create a website/webpage which records information as requested below;
```
If you have other problems like the sound being quiet or the display being wrong in anyway, or if you can't get the stream to work, please send me an email with the following details;
* Browser Type (Chrome, Safari, IE, etc)
* Exact Browser Version (a screenshot of the about page would be awesome!)
* Operating System - as much detail as possible (IE Ubuntu Lucid 64bit)
* The speed and type of Internet connection you have. (IE ADSL, Cable, ADSL2 and 256k, 6M). You can find this information in your ADSL model. 
* Please go to http://www.speedtest.net/ and send me the numbers the widget reports.
* Anything else you think is important.
```

Take inspiration from tools like;
 * http://bugherd.com/
 * http://www.aviusinsight.com/
 * http://www.feedbackferret.com/
 * http://www.userreport.com/
 * http://usersnap.com/

## Further reading

Related issues;
 * Add auto-debugging -- https://github.com/timvideos/streaming-system/issues/3
 * Track client side video quality and performance -- https://github.com/timvideos/streaming-system/issues/44

# Knowledge Prerequisites

 * Javascript
 * HTML

# Contacts

 * **Potential Mentors:** TimVideos Streaming System Hackers team

**Comment by aps-sids** [comment]
@Niharika29 Please send a PR.

**Comment by mithro** [comment]
Ping?

**Comment by Niharika29** [comment]
Just saw, sorry. :( 
I can send in a PR, but the app is not integrated with the existing tim-videos setup. It only adds a link at the bottom.
