### ISSUE TITLE
[flumotion] Port Flumotion to the gstreamer-1.0 API

### ISSUE THREAD

**Issue by mithro** [timvideos/getting-started#9]
# Brief explanation

TimVideos.us makes heavy usage of flumotion for the backend of the streaming system. Flumotion currently uses the gstreamer0.10 API which is now End of Lifed. We need to port it to the gstreamer-1.0 API.

## Expected results

 * Flumotion which runs on gstreamer-1.0
 * Comprehensive flumotion test suite.

# Detailed Explanation

> Flumotion is an award winning streaming software created in 2006 by a group of open source developers and multimedia experts. Flumotion Streaming Software allows broadcasters and companies to stream content live and on demand in all the leading formats from a single server.

**flumotion is written in Python and uses GStreamer and Twisted**

Gstreamer has recently moved to 1.0 - see the following announcement, we need to port to the new API.

> GStreamer 0.10 no longer maintained
>
>2013-03-15 10:00
>Since this has never been announced officially outside of the conference circuit, the GStreamer team would like to clarify that GStreamer 0.10 is no longer maintained. Not by us, nor by anyone else. There will be no more GStreamer 0.10 releases, not even bug-fix releases. Bugs will not be investigated unless they also apply to GStreamer 1.x. Patches will only be reviewed and pushed if they apply to one of the current 1.x branches or fix an issue that still pertains to 1.x. Bug fixes have not been backported systematically to 0.10 for a very long time now, and there are many hundreds of bugs that have only been fixed in 1.x, and manymore are fixed every week. Any commits to the 0.10 branch are made purely on an ad-hoc basis now, and we may lock down the branch completely. No more features will be added to 0.10. However, GStreamer 0.10 support is of course still available on a commercial basis from the usual suspects.
>
>We realise and regret that this may cause some inconvenience, and we also understand that there are circumstances where there are valid reasons not to migrate to 1.0 at this time, or in some cases ever, but we would also like to dispel any doubt whatsoever that there is any other way. We have neither the resources, nor the will or the energy to maintain more than one major version. We must use the little resources we have on code that has a future.
>
>We are happy to provide help and advice to anyone migrating to 1.0. If there are plugins that haven't been ported yet that you need, let us know, maybe we can help get them ported.
>
>Thanks for your understanding.
>
>Happy hacking, see you on the other side!
>
-> Your GStreamer maintainers and release managers

## Further reading

 * [Port your Python app to PyGI, Gtk3, and GStreamer 1.0!](https://wiki.ubuntu.com/Novacut/GStreamer1.0)
 * [Previous GSoC attempt at this project](https://github.com/timvideos/flumotion/tree/gst1.0-attempt-1) [Blog from previous GSoC](http://portingflumotion.blogspot.com/)
 * [flumotion dev guide](https://code.flumotion.com/trac/wiki/Documentation/DeveloperIntroduction)
 * (http://wiki.pitivi.org/wiki/PyGST_Tutorial)
 * (http://valadoc.org/#!wiki=gstreamer-1.0/example-listing-2-gstreamer-concepts) (Not Python, but looks nice)

# Knowledge Prerequisites

 * Strong python coding ability.
 * Twisted experiance very useful.
 * Some gstreamer experience useful.

# Contacts

 * **Potential Mentors:** @mithro
 * **Mailing list:** [timvideos@groups.google.com](http://https://groups.google.com/forum/#!forum/timvideos/)

**Comment by acornejo** [comment]
was this port finished?

**Comment by mithro** [comment]
@aps-sids 's final report can be found at https://docs.google.com/document/d/1Pphn5EEBYE5YhY8B2EYUAqBOQ-Xgazfygv_G1I8VoRU/edit

From that report;
> By the end of these amazing 3 months, I am able to run Flumotion on Ubuntu 14.04 Trusty and create test streams that work as they should. There need to be some improvements which I will be working on even after GSoC ends.

The document includes how to replicate his results.

**Comment by aps-sids** [comment]
@acornejo Most of the components work. Issues are still there, some of which are filed here - https://github.com/aps-sids/flumotion-orig/issues

**Comment by mithro** [comment]
I'm closing this issue as @aps-sids said most components work now.
